---
- name: Pull docker image of Calculator
  hosts: akanksha
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull barivikranth36/spe_miniproject:latest

    - name: running container
      shell: docker run -it -d barivikranth36/spe_miniproject:latest
